#!/bin/bash

# release list: https://github.com/containerd/containerd/releases

if [ ! -f "/usr/local/bin/ctr" ]
then
    echo "ctr is not installed. Installing now... (if prompted, enter password for sudo)"
    curl -L "https://github.com/containerd/containerd/releases/download/v1.3.7/containerd-1.3.7-linux-amd64.tar.gz" -o "/tmp/ctr.tar.gz"
    pushd /tmp
    tar -xzf ctr.tar.gz
    sudo mv /tmp/bin/ctr /usr/local/bin/ctr
    rm -rf /tmp/bin /tmp/ctr.tar.gz
    popd
    exec /usr/local/bin/ctr $@
else
    exec /usr/local/bin/ctr $@
fi
