#!/bin/bash

if [ ! -f "/usr/local/bin/k3s" ]
then
    echo "k3s is not installed. Installing now... (if prompted, enter password for sudo)"
    sudo curl -Lo /usr/local/bin/k3s https://github.com/k3s-io/k3s/releases/download/v1.23.6%2Bk3s1/k3s
    sudo chmod a+x "/usr/local/bin/k3s"
    exec /usr/local/bin/k3s $@
else
    exec /usr/local/bin/k3s $@
fi
