#!/bin/bash

# release list: https://github.com/hashicorp/terraform/releases

if [ ! -f "/usr/local/bin/terraform" ]
then
    echo "terraform is not installed. Installing now... (if prompted, enter password for sudo)"
    curl -L "https://releases.hashicorp.com/terraform/1.5.3/terraform_1.5.3_linux_amd64.zip" -o "/tmp/terraform.zip"
    pushd /tmp
    unzip terraform.zip
    sudo mv /tmp/terraform /usr/local/bin/terraform
    rm -rf /tmp/terraform.zip
    popd
    exec /usr/local/bin/terraform $@
else
    exec /usr/local/bin/terraform $@
fi
